In [1]:
from OurTrainingTools2D import *

=========== Random Seed: 788 ===========


## GW

In [6]:
DataFolder = '/data3/WZ_new_project/h5/Ideal_Data'

td = OurTrainingData([DataFolder + '/ChP_pt300_sm_1.h5',
                     ],
                    [DataFolder + '/ChP_pt300_gwm5e-2.h5',
                     DataFolder + '/ChP_pt300_gwm1e-1.h5',
                     DataFolder + '/ChP_pt300_gwm2e-1.h5',                     
                     DataFolder + '/ChP_pt300_gw5e-2.h5',
                     DataFolder + '/ChP_pt300_gw1e-1.h5',
                     DataFolder + '/ChP_pt300_gw2e-1.h5'],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

random_seed = torch.randint(0, 1339, (1,)).item()
OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChPgw_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')


td = OurTrainingData([DataFolder + '/ChM_pt300_sm_1.h5',
                     ],
                     [DataFolder + '/ChM_pt300_gwm5e-2.h5',
                     DataFolder + '/ChM_pt300_gwm1e-1.h5',
                     DataFolder + '/ChM_pt300_gwm2e-1.h5',                     
                     DataFolder + '/ChM_pt300_gw5e-2.h5',
                     DataFolder + '/ChM_pt300_gw1e-1.h5',
                     DataFolder + '/ChM_pt300_gw2e-1.h5'],
                     process = 'W-Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChMgW_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gwm5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.05}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gwm5e-2.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gwm1e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.1}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gwm1e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gwm2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.2}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Conver

#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChM_pt300_gw2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., 0.2}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_gw2e-1.dat.gz
Charge = -1 --- Process = W-Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChM_pt300_sm_1.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_sm_1.dat.gz
Charge = -1 --- Process = W-Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=torch.float64)  3000000         0.329009

Loaded BSM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']                     #Data    XS[pb](avg.w)
----------------------------------------------

OurCDModel(
  (LinearLayers): ModuleList(
    (0): Linear(in_features=9, out_features=32, bias=True)
    (1): Linear(in_features=32, out_features=32, bias=True)
    (2): Linear(in_features=32, out_features=32, bias=True)
    (3): Linear(in_features=32, out_features=1, bias=True)
    (4): Linear(in_features=9, out_features=32, bias=True)
    (5): Linear(in_features=32, out_features=32, bias=True)
    (6): Linear(in_features=32, out_features=32, bias=True)
    (7): Linear(in_features=32, out_features=1, bias=True)
    (8): Linear(in_features=9, out_features=32, bias=True)
    (9): Linear(in_features=32, out_features=32, bias=True)
    (10): Linear(in_features=32, out_features=32, bias=True)
    (11): Linear(in_features=32, out_features=1, bias=True)
    (12): Linear(in_features=9, out_features=32, bias=True)
    (13): Linear(in_features=32, out_features=32, bias=True)
    (14): Linear(in_features=32, out_features=32, bias=True)
    (15): Linear(in_features=32, out_features=1, bias=True)


In [7]:
DataFolder = '/data3/WZ_new_project/h5/Ideal_Data'

td = OurTrainingData([DataFolder + '/ChP_pt300_sm_1.h5',
                     ],
                    [DataFolder + '/ChP_pt300_gwm5e-2.h5',
                     DataFolder + '/ChP_pt300_gwm1e-1.h5',
                     DataFolder + '/ChP_pt300_gwm2e-1.h5',                     
                     DataFolder + '/ChP_pt300_gw5e-2.h5',
                     DataFolder + '/ChP_pt300_gw1e-1.h5',
                     DataFolder + '/ChP_pt300_gw2e-1.h5'],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

random_seed = torch.randint(0, 1339, (1,)).item()
OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChPgw_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')


td = OurTrainingData([DataFolder + '/ChM_pt300_sm_1.h5',
                     ],
                     [DataFolder + '/ChM_pt300_gwm5e-2.h5',
                     DataFolder + '/ChM_pt300_gwm1e-1.h5',
                     DataFolder + '/ChM_pt300_gwm2e-1.h5',                     
                     DataFolder + '/ChM_pt300_gw5e-2.h5',
                     DataFolder + '/ChM_pt300_gw1e-1.h5',
                     DataFolder + '/ChM_pt300_gw2e-1.h5'],
                     process = 'W-Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChMgW_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gwm5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.05}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gwm5e-2.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gwm1e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.1}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gwm1e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gwm2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.2}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Conver

#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChM_pt300_sm_1.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_sm_1.dat.gz
Charge = -1 --- Process = W-Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=torch.float64)  3000000         0.329009

Loaded BSM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']                     #Data    XS[pb](avg.w)
-------------------------------------------------  -------  ---------------
tensor([[ 0.0000, -0.0500]], dtype=torch.float64)   500000         0.358355
tensor([[ 0.0000, -0.1000]], dtype=torch.float64)   500000         0.446333
tensor([[ 0.0000, -0.2000]], dtype=torch.float64)   500000         0.798199
tensor([[0.0000, 0.0500]], dtype=torch.float64)     500000         0.358314


OurCDModel(
  (LinearLayers): ModuleList(
    (0): Linear(in_features=9, out_features=32, bias=True)
    (1): Linear(in_features=32, out_features=32, bias=True)
    (2): Linear(in_features=32, out_features=32, bias=True)
    (3): Linear(in_features=32, out_features=1, bias=True)
    (4): Linear(in_features=9, out_features=32, bias=True)
    (5): Linear(in_features=32, out_features=32, bias=True)
    (6): Linear(in_features=32, out_features=32, bias=True)
    (7): Linear(in_features=32, out_features=1, bias=True)
    (8): Linear(in_features=9, out_features=32, bias=True)
    (9): Linear(in_features=32, out_features=32, bias=True)
    (10): Linear(in_features=32, out_features=32, bias=True)
    (11): Linear(in_features=32, out_features=1, bias=True)
    (12): Linear(in_features=9, out_features=32, bias=True)
    (13): Linear(in_features=32, out_features=32, bias=True)
    (14): Linear(in_features=32, out_features=32, bias=True)
    (15): Linear(in_features=32, out_features=1, bias=True)


## Gphi

In [2]:
DataFolder = '/data3/WZ_new_project/h5/Ideal_Data'

td = OurTrainingData([DataFolder + '/ChP_pt300_sm_1.h5',
                     ],
                     #DataFolder + '/ChP_pt300_sm_2.h5',
                    #DataFolder + '/ChP_pt300_sm_3.h5'],
                    [DataFolder + '/ChP_pt300_gphim5e-1.h5',
                     DataFolder + '/ChP_pt300_gphim2e-1.h5',
                     DataFolder + '/ChP_pt300_gphim5e-2.h5',
                     DataFolder + '/ChP_pt300_gphi5e-1.h5',
                     DataFolder + '/ChP_pt300_gphi2e-1.h5',
                     DataFolder + '/ChP_pt300_gphi5e-2.h5'],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

random_seed = torch.randint(0, 1339, (1,)).item()
OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChPgphi_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')


td = OurTrainingData([DataFolder + '/ChM_pt300_sm_1.h5',
                     ],
                     
                     #DataFolder + '/ChM_pt300_sm_2.h5',
                     #DataFolder + '/ChP_pt300_sm_3.h5'],
                    [DataFolder + '/ChM_pt300_gphim5e-1.h5',
                     DataFolder + '/ChM_pt300_gphim2e-1.h5',
                     DataFolder + '/ChM_pt300_gphim5e-2.h5',
                     DataFolder + '/ChM_pt300_gphi5e-1.h5',
                     DataFolder + '/ChM_pt300_gphi2e-1.h5',
                     DataFolder + '/ChM_pt300_gphi5e-2.h5'],
                     process = 'W-Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChMgphi_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim5e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.5, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphim5e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.2, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphim2e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.05, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weigh

/home/chen/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


Training epoch 100 (took 290.94 sec, time left 8:50:10.362839 sec) loss 0.13897339
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChPgphi_par, (16 BSM, 500k, CD, Seed700), 100 epoch.pth
Training epoch 500 (took 1073.25 sec, time left 7:21:42.745585 sec) loss 0.12583785
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChPgphi_par, (16 BSM, 500k, CD, Seed700), 500 epoch.pth
Training epoch 1000 (took 1257.04 sec, time left 6:37:47.205526 sec) loss 0.12477845
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChPgphi_par, (16 BSM, 500k, CD, Seed700), 1000 epoch.pth
Training epoch 2000 (took 2487.97 sec, time left 5:42:38.483825 sec) loss 0.12433519
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChPgphi_par, (16 BSM, 500k, CD, Seed700), 2000 epoch.pth
Training epoch 3000 (took 2505.75 sec, time left 4:57:18.214255 sec) loss 0.12418

Training epoch 4000 (took 2364.79 sec, time left 3:56:47.630029 sec) loss 0.13076273
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChMgphi_par, (16 BSM, 500k, CD, Seed700), 4000 epoch.pth
Training epoch 5000 (took 2358.20 sec, time left 3:17:09.174864 sec) loss 0.13072272
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChMgphi_par, (16 BSM, 500k, CD, Seed700), 5000 epoch.pth
Training epoch 6000 (took 2373.78 sec, time left 2:37:47.849817 sec) loss 0.13068593
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChMgphi_par, (16 BSM, 500k, CD, Seed700), 6000 epoch.pth
Training epoch 7000 (took 2361.01 sec, time left 1:58:17.492458 sec) loss 0.13065587
Model successfully saved.
Path: /home/chen/Documents/2DQuadraticClassifier/TrainedModels/ChMgphi_par, (16 BSM, 500k, CD, Seed700), 7000 epoch.pth
Training epoch 8000 (took 2370.51 sec, time left 1:18:51.845400 sec) loss 0.

OurCDModel(
  (LinearLayers): ModuleList(
    (0): Linear(in_features=9, out_features=32, bias=True)
    (1): Linear(in_features=32, out_features=32, bias=True)
    (2): Linear(in_features=32, out_features=32, bias=True)
    (3): Linear(in_features=32, out_features=1, bias=True)
    (4): Linear(in_features=9, out_features=32, bias=True)
    (5): Linear(in_features=32, out_features=32, bias=True)
    (6): Linear(in_features=32, out_features=32, bias=True)
    (7): Linear(in_features=32, out_features=1, bias=True)
    (8): Linear(in_features=9, out_features=32, bias=True)
    (9): Linear(in_features=32, out_features=32, bias=True)
    (10): Linear(in_features=32, out_features=32, bias=True)
    (11): Linear(in_features=32, out_features=1, bias=True)
    (12): Linear(in_features=9, out_features=32, bias=True)
    (13): Linear(in_features=32, out_features=32, bias=True)
    (14): Linear(in_features=32, out_features=32, bias=True)
    (15): Linear(in_features=32, out_features=1, bias=True)


In [4]:
DataFolder = '/data3/WZ_new_project/h5/Ideal_Data'

td = OurTrainingData([DataFolder + '/ChP_pt300_sm_1.h5',
                     ],
                     #DataFolder + '/ChP_pt300_sm_2.h5',
                    #DataFolder + '/ChP_pt300_sm_3.h5'],
                    [DataFolder + '/ChP_pt300_gphim5e-1.h5',
                     DataFolder + '/ChP_pt300_gphim2e-1.h5',
                     DataFolder + '/ChP_pt300_gphim5e-2.h5',
                     DataFolder + '/ChP_pt300_gphi5e-1.h5',
                     DataFolder + '/ChP_pt300_gphi2e-1.h5',
                     DataFolder + '/ChP_pt300_gphi5e-2.h5'],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

random_seed = torch.randint(0, 1339, (1,)).item()
OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChPgphi_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')


td = OurTrainingData([DataFolder + '/ChM_pt300_sm_1.h5',
                     ],
                     
                     #DataFolder + '/ChM_pt300_sm_2.h5',
                     #DataFolder + '/ChP_pt300_sm_3.h5'],
                    [DataFolder + '/ChM_pt300_gphim5e-1.h5',
                     DataFolder + '/ChM_pt300_gphim2e-1.h5',
                     DataFolder + '/ChM_pt300_gphim5e-2.h5',
                     DataFolder + '/ChM_pt300_gphi5e-1.h5',
                     DataFolder + '/ChM_pt300_gphi2e-1.h5',
                     DataFolder + '/ChM_pt300_gphi5e-2.h5'],
                     process = 'W-Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChMgphi_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim5e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.5, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphim5e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.2, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphim2e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.05, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weigh

##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.2, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_gphi2e-1.dat.gz
Charge = -1 --- Process = W-Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChM_pt300_gphi5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.05, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_gphi5e-2.dat.gz
Charge = -1 --- Process = W-Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChM_pt300_sm_1.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_sm_1.dat.gz
Charge = -1 --- Process = W-Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
-----------

OurCDModel(
  (LinearLayers): ModuleList(
    (0): Linear(in_features=9, out_features=32, bias=True)
    (1): Linear(in_features=32, out_features=32, bias=True)
    (2): Linear(in_features=32, out_features=32, bias=True)
    (3): Linear(in_features=32, out_features=1, bias=True)
    (4): Linear(in_features=9, out_features=32, bias=True)
    (5): Linear(in_features=32, out_features=32, bias=True)
    (6): Linear(in_features=32, out_features=32, bias=True)
    (7): Linear(in_features=32, out_features=1, bias=True)
    (8): Linear(in_features=9, out_features=32, bias=True)
    (9): Linear(in_features=32, out_features=32, bias=True)
    (10): Linear(in_features=32, out_features=32, bias=True)
    (11): Linear(in_features=32, out_features=1, bias=True)
    (12): Linear(in_features=9, out_features=32, bias=True)
    (13): Linear(in_features=32, out_features=32, bias=True)
    (14): Linear(in_features=32, out_features=32, bias=True)
    (15): Linear(in_features=32, out_features=1, bias=True)


In [5]:
DataFolder = '/data3/WZ_new_project/h5/Ideal_Data'

td = OurTrainingData([DataFolder + '/ChP_pt300_sm_1.h5',
                     ],
                     #DataFolder + '/ChP_pt300_sm_2.h5',
                    #DataFolder + '/ChP_pt300_sm_3.h5'],
                    [DataFolder + '/ChP_pt300_gphim5e-1.h5',
                     DataFolder + '/ChP_pt300_gphim2e-1.h5',
                     DataFolder + '/ChP_pt300_gphim5e-2.h5',
                     DataFolder + '/ChP_pt300_gphi5e-1.h5',
                     DataFolder + '/ChP_pt300_gphi2e-1.h5',
                     DataFolder + '/ChP_pt300_gphi5e-2.h5'],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

random_seed = torch.randint(0, 1339, (1,)).item()
OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChPgphi_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')


td = OurTrainingData([DataFolder + '/ChM_pt300_sm_1.h5',
                     ],
                     
                     #DataFolder + '/ChM_pt300_sm_2.h5',
                     #DataFolder + '/ChP_pt300_sm_3.h5'],
                    [DataFolder + '/ChM_pt300_gphim5e-1.h5',
                     DataFolder + '/ChM_pt300_gphim2e-1.h5',
                     DataFolder + '/ChM_pt300_gphim5e-2.h5',
                     DataFolder + '/ChM_pt300_gphi5e-1.h5',
                     DataFolder + '/ChM_pt300_gphi2e-1.h5',
                     DataFolder + '/ChM_pt300_gphi5e-2.h5'],
                     process = 'W-Z', parameters =['Gphi[TeV**-2]', 'GW[TeV**-2]'], 
                     SMNLimits=int(3e6),
                     BSMNLimits=int(5e5))

NumEpochs = int(1e4)

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

MD = OurCDModel(NumberOfParameters=2, AR=[9,32,32,32,1])
MD.InitPreprocess(Data, ParVal)

OT = OurTrainer(NumEpochs = NumEpochs)
OT.SetSaveAfterEpochs([10,100,500]+list(range(1000, 11000, 1000)))

OT.Train(MD, Data = Data, Parameters = ParVal, Labels=Labels, Weights= Weights, bs = 100000,
        Name = 'ChMgphi_par, (16 BSM, 500k, CD, Seed%d), '%(random_seed), Folder = os.getcwd()+'/TrainedModels/')

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim5e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.5, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphim5e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.2, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphim2e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChP_pt300_gphim5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {-0.05, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weigh

##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.2, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_gphi2e-1.dat.gz
Charge = -1 --- Process = W-Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChM_pt300_gphi5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.05, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_gphi5e-2.dat.gz
Charge = -1 --- Process = W-Z
#####

Reading file .../data3/WZ_new_project/h5/Ideal_Data/ChM_pt300_sm_1.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChM_pt300_sm_1.dat.gz
Charge = -1 --- Process = W-Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
-----------

KeyboardInterrupt: 